export const stocks ={
  "data": [
    {
      "ticker": "SPEC",
      "figi_ticker": "SPEC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 54.6,
      "high": 54.6,
      "low": 54.6,
      "close": 54.6,
      "volume": 1000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 54.6,
      "adj_high": 54.6,
      "adj_low": 54.6,
      "adj_close": 54.6,
      "adj_volume": 1000
    },
    {
      "ticker": "AJWAN",
      "figi_ticker": "AJWAN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 21.3,
      "high": 21.5,
      "low": 20.8,
      "close": 21.5,
      "volume": 847600,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 21.3,
      "adj_high": 21.5,
      "adj_low": 20.8,
      "adj_close": 21.5,
      "adj_volume": 847600
    },
    {
      "ticker": "EFFECT",
      "figi_ticker": "EFFECT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 17.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 17.5,
      "adj_volume": 0
    },
    {
      "ticker": "MEZZAN",
      "figi_ticker": "MEZZAN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 729,
      "high": 729,
      "low": 720,
      "close": 720,
      "volume": 509628,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 729,
      "adj_high": 729,
      "adj_low": 720,
      "adj_close": 720,
      "adj_volume": 509628
    },
    {
      "ticker": "VIVA",
      "figi_ticker": "VIVA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 720,
      "high": 734,
      "low": 706,
      "close": 706,
      "volume": 31613,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 720,
      "adj_high": 734,
      "adj_low": 706,
      "adj_close": 706,
      "adj_volume": 31613
    },
    {
      "ticker": "WARBABANK",
      "figi_ticker": "WARBABANK:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 241,
      "high": 245,
      "low": 241,
      "close": 243,
      "volume": 1386766,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 241,
      "adj_high": 245,
      "adj_low": 241,
      "adj_close": 243,
      "adj_volume": 1386766
    },
    {
      "ticker": "ITHMR",
      "figi_ticker": "ITHMR:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 31,
      "high": 32,
      "low": 31,
      "close": 31.6,
      "volume": 879050,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 31,
      "adj_high": 32,
      "adj_low": 31,
      "adj_close": 31.6,
      "adj_volume": 879050
    },
    {
      "ticker": "AUB",
      "figi_ticker": "AUB:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 182,
      "high": 182,
      "low": 180,
      "close": 181,
      "volume": 1163280,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 182,
      "adj_high": 182,
      "adj_low": 180,
      "adj_close": 181,
      "adj_volume": 1163280
    },
    {
      "ticker": "INOVEST",
      "figi_ticker": "INOVEST:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 72,
      "high": 72,
      "low": 69,
      "close": 72,
      "volume": 140036,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 72,
      "adj_high": 72,
      "adj_low": 69,
      "adj_close": 72,
      "adj_volume": 140036
    },
    {
      "ticker": "EKHOLDING",
      "figi_ticker": "EKHOLDING:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 307.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 307.5,
      "adj_volume": 0
    },
    {
      "ticker": "GFH",
      "figi_ticker": "GFH:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 100,
      "high": 101,
      "low": 100,
      "close": 101,
      "volume": 299260,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 100,
      "adj_high": 101,
      "adj_low": 100,
      "adj_close": 101,
      "adj_volume": 299260
    },
    {
      "ticker": "RKWC",
      "figi_ticker": "RKWC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 78.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 78.5,
      "adj_volume": 0
    },
    {
      "ticker": "FCEM",
      "figi_ticker": "FCEM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 72.55,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 72.55,
      "adj_volume": 0
    },
    {
      "ticker": "SCEM",
      "figi_ticker": "SCEM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 77.45,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 77.45,
      "adj_volume": 0
    },
    {
      "ticker": "GCEM",
      "figi_ticker": "GCEM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 83.5,
      "high": 83.5,
      "low": 83.5,
      "close": 83.5,
      "volume": 10000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 83.5,
      "adj_high": 83.5,
      "adj_low": 83.5,
      "adj_close": 83.5,
      "adj_volume": 10000
    },
    {
      "ticker": "DANAH",
      "figi_ticker": "DANAH:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 47,
      "high": 49.5,
      "low": 47,
      "close": 48.5,
      "volume": 812004,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 47,
      "adj_high": 49.5,
      "adj_low": 47,
      "adj_close": 48.5,
      "adj_volume": 812004
    },
    {
      "ticker": "CATTL",
      "figi_ticker": "CATTL:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 216.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 216.5,
      "adj_volume": 0
    },
    {
      "ticker": "ALRAI",
      "figi_ticker": "ALRAI:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 128,
      "high": 128,
      "low": 128,
      "close": 128,
      "volume": 148,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 128,
      "adj_high": 128,
      "adj_low": 128,
      "adj_close": 128,
      "adj_volume": 148
    },
    {
      "ticker": "LOGISTICS",
      "figi_ticker": "LOGISTICS:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 46.8,
      "high": 46.8,
      "low": 45.9,
      "close": 45.9,
      "volume": 447983,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 46.8,
      "adj_high": 46.8,
      "adj_low": 45.9,
      "adj_close": 45.9,
      "adj_volume": 447983
    },
    {
      "ticker": "SOOR",
      "figi_ticker": "SOOR:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 114,
      "high": 117,
      "low": 113,
      "close": 113,
      "volume": 11081,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 114,
      "adj_high": 117,
      "adj_low": 113,
      "adj_close": 113,
      "adj_volume": 11081
    },
    {
      "ticker": "JAZEERA",
      "figi_ticker": "JAZEERA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 640,
      "high": 640,
      "low": 640,
      "close": 640,
      "volume": 72626,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 640,
      "adj_high": 640,
      "adj_low": 640,
      "adj_close": 640,
      "adj_volume": 72626
    },
    {
      "ticker": "MUNTAZAHAT",
      "figi_ticker": "MUNTAZAHAT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 57,
      "high": 58.9,
      "low": 57,
      "close": 57,
      "volume": 374207,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 57,
      "adj_high": 58.9,
      "adj_low": 57,
      "adj_close": 57,
      "adj_volume": 374207
    },
    {
      "ticker": "MUBARRAD",
      "figi_ticker": "MUBARRAD:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 66,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 66,
      "adj_volume": 0
    },
    {
      "ticker": "HAYATCOMM",
      "figi_ticker": "HAYATCOMM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 67.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 67.5,
      "adj_volume": 0
    },
    {
      "ticker": "OULAFUEL",
      "figi_ticker": "OULAFUEL:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 112,
      "high": 113,
      "low": 112,
      "close": 113,
      "volume": 7202,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 112,
      "adj_high": 113,
      "adj_low": 112,
      "adj_close": 113,
      "adj_volume": 7202
    },
    {
      "ticker": "ALAFCO",
      "figi_ticker": "ALAFCO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 357,
      "high": 360,
      "low": 357,
      "close": 358,
      "volume": 192823,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 357,
      "adj_high": 360,
      "adj_low": 357,
      "adj_close": 358,
      "adj_volume": 192823
    },
    {
      "ticker": "UPAC",
      "figi_ticker": "UPAC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 725,
      "high": 725,
      "low": 690,
      "close": 690,
      "volume": 13767,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 725,
      "adj_high": 725,
      "adj_low": 690,
      "adj_close": 690,
      "adj_volume": 13767
    },
    {
      "ticker": "PAPCO",
      "figi_ticker": "PAPCO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 45,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 45,
      "adj_volume": 0
    },
    {
      "ticker": "CGC",
      "figi_ticker": "CGC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 432,
      "high": 433,
      "low": 432,
      "close": 433,
      "volume": 12635,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 432,
      "adj_high": 433,
      "adj_low": 432,
      "adj_close": 433,
      "adj_volume": 12635
    },
    {
      "ticker": "TAHSSILAT",
      "figi_ticker": "TAHSSILAT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 19.2,
      "high": 23,
      "low": 19.2,
      "close": 20.7,
      "volume": 3500,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 19.2,
      "adj_high": 23,
      "adj_low": 19.2,
      "adj_close": 20.7,
      "adj_volume": 3500
    },
    {
      "ticker": "GPI",
      "figi_ticker": "GPI:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 26,
      "high": 26.5,
      "low": 26,
      "close": 26.2,
      "volume": 1328306,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 26,
      "adj_high": 26.5,
      "adj_low": 26,
      "adj_close": 26.2,
      "adj_volume": 1328306
    },
    {
      "ticker": "ENERGYH",
      "figi_ticker": "ENERGYH:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 27.8,
      "high": 27.8,
      "low": 27.8,
      "close": 27.8,
      "volume": 250,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 27.8,
      "adj_high": 27.8,
      "adj_low": 27.8,
      "adj_close": 27.8,
      "adj_volume": 250
    },
    {
      "ticker": "KPPC",
      "figi_ticker": "KPPC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 58.1,
      "high": 61.5,
      "low": 58.1,
      "close": 60.5,
      "volume": 4024072,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 58.1,
      "adj_high": 61.5,
      "adj_low": 58.1,
      "adj_close": 60.5,
      "adj_volume": 4024072
    },
    {
      "ticker": "HUMANSOFT",
      "figi_ticker": "HUMANSOFT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 3920,
      "high": 3949,
      "low": 3880,
      "close": 3949,
      "volume": 238344,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 3920,
      "adj_high": 3949,
      "adj_low": 3880,
      "adj_close": 3949,
      "adj_volume": 238344
    },
    {
      "ticker": "KCPC",
      "figi_ticker": "KCPC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 161,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 161,
      "adj_volume": 0
    },
    {
      "ticker": "NAPESCO",
      "figi_ticker": "NAPESCO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 725,
      "high": 725,
      "low": 725,
      "close": 725,
      "volume": 10,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 725,
      "adj_high": 725,
      "adj_low": 725,
      "adj_close": 725,
      "adj_volume": 10
    },
    {
      "ticker": "ASC",
      "figi_ticker": "ASC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 160,
      "high": 160,
      "low": 150,
      "close": 151,
      "volume": 10000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 160,
      "adj_high": 160,
      "adj_low": 150,
      "adj_close": 151,
      "adj_volume": 10000
    },
    {
      "ticker": "OOREDOO",
      "figi_ticker": "OOREDOO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 875,
      "high": 899,
      "low": 870,
      "close": 870,
      "volume": 20510,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 875,
      "adj_high": 899,
      "adj_low": 870,
      "adj_close": 870,
      "adj_volume": 20510
    },
    {
      "ticker": "AGHC",
      "figi_ticker": "AGHC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 72.75,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 72.75,
      "adj_volume": 0
    },
    {
      "ticker": "CLEANING",
      "figi_ticker": "CLEANING:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 51,
      "high": 55.5,
      "low": 51,
      "close": 55,
      "volume": 17717,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 51,
      "adj_high": 55.5,
      "adj_low": 51,
      "adj_close": 55,
      "adj_volume": 17717
    },
    {
      "ticker": "EDU",
      "figi_ticker": "EDU:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 314,
      "high": 315,
      "low": 309,
      "close": 310,
      "volume": 40800,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 314,
      "adj_high": 315,
      "adj_low": 309,
      "adj_close": 310,
      "adj_volume": 40800
    },
    {
      "ticker": "IPG",
      "figi_ticker": "IPG:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 410,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 410,
      "adj_volume": 0
    },
    {
      "ticker": "SENERGY",
      "figi_ticker": "SENERGY:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 26.45,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 26.45,
      "adj_volume": 0
    },
    {
      "ticker": "ZAIN",
      "figi_ticker": "ZAIN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 417,
      "high": 419,
      "low": 413,
      "close": 413,
      "volume": 1166009,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 417,
      "adj_high": 419,
      "adj_low": 413,
      "adj_close": 413,
      "adj_volume": 1166009
    },
    {
      "ticker": "AGLTY",
      "figi_ticker": "AGLTY:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 836,
      "high": 836,
      "low": 829,
      "close": 833,
      "volume": 292959,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 836,
      "adj_high": 836,
      "adj_low": 829,
      "adj_close": 833,
      "adj_volume": 292959
    },
    {
      "ticker": "KCIN",
      "figi_ticker": "KCIN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 1049.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 1049.5,
      "adj_volume": 0
    },
    {
      "ticker": "BIIHC",
      "figi_ticker": "BIIHC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 27,
      "high": 30,
      "low": 27,
      "close": 29.7,
      "volume": 17870,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 27,
      "adj_high": 30,
      "adj_low": 27,
      "adj_close": 29.7,
      "adj_volume": 17870
    },
    {
      "ticker": "SALBOOKH",
      "figi_ticker": "SALBOOKH:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 42,
      "high": 42,
      "low": 42,
      "close": 42,
      "volume": 137321,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 42,
      "adj_high": 42,
      "adj_low": 42,
      "adj_close": 42,
      "adj_volume": 137321
    },
    {
      "ticker": "ALQURAIN",
      "figi_ticker": "ALQURAIN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 349,
      "high": 349,
      "low": 348,
      "close": 348,
      "volume": 45549,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 349,
      "adj_high": 349,
      "adj_low": 348,
      "adj_close": 348,
      "adj_volume": 45549
    },
    {
      "ticker": "NCCI",
      "figi_ticker": "NCCI:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 40.35,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 40.35,
      "adj_volume": 0
    },
    {
      "ticker": "EQUIPMENT",
      "figi_ticker": "EQUIPMENT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 30.2,
      "high": 30.6,
      "low": 29.1,
      "close": 30.4,
      "volume": 836257,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 30.2,
      "adj_high": 30.6,
      "adj_low": 29.1,
      "adj_close": 30.4,
      "adj_volume": 836257
    },
    {
      "ticker": "NICBM",
      "figi_ticker": "NICBM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 170,
      "high": 170,
      "low": 170,
      "close": 170,
      "volume": 1000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 170,
      "adj_high": 170,
      "adj_low": 170,
      "adj_close": 170,
      "adj_volume": 1000
    },
    {
      "ticker": "BPCC",
      "figi_ticker": "BPCC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 817,
      "high": 817,
      "low": 817,
      "close": 817,
      "volume": 25534,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 817,
      "adj_high": 817,
      "adj_low": 817,
      "adj_close": 817,
      "adj_volume": 25534
    },
    {
      "ticker": "ACICO",
      "figi_ticker": "ACICO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 242.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 242.5,
      "adj_volume": 0
    },
    {
      "ticker": "KFOUC",
      "figi_ticker": "KFOUC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 250,
      "high": 250,
      "low": 250,
      "close": 250,
      "volume": 10,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 250,
      "adj_high": 250,
      "adj_low": 250,
      "adj_close": 250,
      "adj_volume": 10
    },
    {
      "ticker": "PAPER",
      "figi_ticker": "PAPER:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 240,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 240,
      "adj_volume": 0
    },
    {
      "ticker": "PCEM",
      "figi_ticker": "PCEM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 1070,
      "high": 1070,
      "low": 1068,
      "close": 1070,
      "volume": 34128,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 1070,
      "adj_high": 1070,
      "adj_low": 1068,
      "adj_close": 1070,
      "adj_volume": 34128
    },
    {
      "ticker": "SHIP",
      "figi_ticker": "SHIP:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 299,
      "high": 308,
      "low": 297,
      "close": 308,
      "volume": 2245170,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 299,
      "adj_high": 308,
      "adj_low": 297,
      "adj_close": 308,
      "adj_volume": 2245170
    },
    {
      "ticker": "CABLE",
      "figi_ticker": "CABLE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 399,
      "high": 399,
      "low": 399,
      "close": 399,
      "volume": 10000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 399,
      "adj_high": 399,
      "adj_low": 399,
      "adj_close": 399,
      "adj_volume": 10000
    },
    {
      "ticker": "KCEM",
      "figi_ticker": "KCEM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 440,
      "high": 440,
      "low": 435,
      "close": 435,
      "volume": 30000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 440,
      "adj_high": 440,
      "adj_low": 435,
      "adj_close": 435,
      "adj_volume": 30000
    },
    {
      "ticker": "NIND",
      "figi_ticker": "NIND:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 154,
      "high": 156,
      "low": 154,
      "close": 156,
      "volume": 1533650,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 154,
      "adj_high": 156,
      "adj_low": 154,
      "adj_close": 156,
      "adj_volume": 1533650
    },
    {
      "ticker": "MARAKEZ",
      "figi_ticker": "MARAKEZ:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 23,
      "high": 23,
      "low": 20.7,
      "close": 22,
      "volume": 38381,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 23,
      "adj_high": 23,
      "adj_low": 20.7,
      "adj_close": 22,
      "adj_volume": 38381
    },
    {
      "ticker": "ALMUDON",
      "figi_ticker": "ALMUDON:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 31.3,
      "high": 31.3,
      "low": 31.3,
      "close": 31.3,
      "volume": 2555,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 31.3,
      "adj_high": 31.3,
      "adj_low": 31.3,
      "adj_close": 31.3,
      "adj_volume": 2555
    },
    {
      "ticker": "MENA",
      "figi_ticker": "MENA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 60,
      "high": 60,
      "low": 54,
      "close": 54,
      "volume": 150,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 60,
      "adj_high": 60,
      "adj_low": 54,
      "adj_close": 54,
      "adj_volume": 150
    },
    {
      "ticker": "KBT",
      "figi_ticker": "KBT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 43,
      "high": 44.9,
      "low": 43,
      "close": 43,
      "volume": 83300,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 43,
      "adj_high": 44.9,
      "adj_low": 43,
      "adj_close": 43,
      "adj_volume": 83300
    },
    {
      "ticker": "MANAZEL",
      "figi_ticker": "MANAZEL:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 37,
      "high": 38.3,
      "low": 35,
      "close": 38.3,
      "volume": 6421637,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 37,
      "adj_high": 38.3,
      "adj_low": 35,
      "adj_close": 38.3,
      "adj_volume": 6421637
    },
    {
      "ticker": "FIRSTDUBAI",
      "figi_ticker": "FIRSTDUBAI:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 41.3,
      "high": 41.3,
      "low": 39,
      "close": 39,
      "volume": 332390,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 41.3,
      "adj_high": 41.3,
      "adj_low": 39,
      "adj_close": 39,
      "adj_volume": 332390
    },
    {
      "ticker": "MUNSHAAT",
      "figi_ticker": "MUNSHAAT:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 67.8,
      "high": 78,
      "low": 67.8,
      "close": 78,
      "volume": 206140,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 67.8,
      "adj_high": 78,
      "adj_low": 67.8,
      "adj_close": 78,
      "adj_volume": 206140
    },
    {
      "ticker": "ARGAN",
      "figi_ticker": "ARGAN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 152,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 152,
      "adj_volume": 0
    },
    {
      "ticker": "ABYAAR",
      "figi_ticker": "ABYAAR:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 19.2,
      "high": 19.8,
      "low": 19.2,
      "close": 19.6,
      "volume": 1928218,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 19.2,
      "adj_high": 19.8,
      "adj_low": 19.2,
      "adj_close": 19.6,
      "adj_volume": 1928218
    },
    {
      "ticker": "ARKAN",
      "figi_ticker": "ARKAN:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 75,
      "high": 75,
      "low": 74,
      "close": 74,
      "volume": 42550,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 75,
      "adj_high": 75,
      "adj_low": 74,
      "adj_close": 74,
      "adj_volume": 42550
    },
    {
      "ticker": "TAAMEER",
      "figi_ticker": "TAAMEER:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 29,
      "high": 29.5,
      "low": 26.7,
      "close": 29,
      "volume": 190060,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 29,
      "adj_high": 29.5,
      "adj_low": 26.7,
      "adj_close": 29,
      "adj_volume": 190060
    },
    {
      "ticker": "ALAQARIA",
      "figi_ticker": "ALAQARIA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 24.5,
      "high": 24.5,
      "low": 23,
      "close": 23,
      "volume": 90103,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 24.5,
      "adj_high": 24.5,
      "adj_low": 23,
      "adj_close": 23,
      "adj_volume": 90103
    },
    {
      "ticker": "MAZAYA",
      "figi_ticker": "MAZAYA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 98.2,
      "high": 98.6,
      "low": 98.2,
      "close": 98.6,
      "volume": 377980,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 98.2,
      "adj_high": 98.6,
      "adj_low": 98.2,
      "adj_close": 98.6,
      "adj_volume": 377980
    },
    {
      "ticker": "AQAR",
      "figi_ticker": "AQAR:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 73.95,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 73.95,
      "adj_volume": 0
    },
    {
      "ticker": "AAYANRE",
      "figi_ticker": "AAYANRE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 51.3,
      "high": 51.3,
      "low": 51.3,
      "close": 51.3,
      "volume": 40500,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 51.3,
      "adj_high": 51.3,
      "adj_low": 51.3,
      "adj_close": 51.3,
      "adj_volume": 40500
    },
    {
      "ticker": "ALTIJARIA",
      "figi_ticker": "ALTIJARIA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 78.5,
      "high": 78.5,
      "low": 77.3,
      "close": 78,
      "volume": 179600,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 78.5,
      "adj_high": 78.5,
      "adj_low": 77.3,
      "adj_close": 78,
      "adj_volume": 179600
    },
    {
      "ticker": "IRC",
      "figi_ticker": "IRC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 23.9,
      "high": 29.2,
      "low": 23.9,
      "close": 29.2,
      "volume": 584500,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 23.9,
      "adj_high": 29.2,
      "adj_low": 23.9,
      "adj_close": 29.2,
      "adj_volume": 584500
    },
    {
      "ticker": "INVESTORS",
      "figi_ticker": "INVESTORS:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 14.1,
      "high": 14.1,
      "low": 13.8,
      "close": 13.8,
      "volume": 2735456,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 14.1,
      "adj_high": 14.1,
      "adj_low": 13.8,
      "adj_close": 13.8,
      "adj_volume": 2735456
    },
    {
      "ticker": "MABANEE",
      "figi_ticker": "MABANEE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 670,
      "high": 676,
      "low": 670,
      "close": 675,
      "volume": 424277,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 670,
      "adj_high": 676,
      "adj_low": 670,
      "adj_close": 675,
      "adj_volume": 424277
    },
    {
      "ticker": "ERESCO",
      "figi_ticker": "ERESCO:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 32.5,
      "high": 33,
      "low": 32.2,
      "close": 33,
      "volume": 526135,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 32.5,
      "adj_high": 33,
      "adj_low": 32.2,
      "adj_close": 33,
      "adj_volume": 526135
    },
    {
      "ticker": "ARABREC",
      "figi_ticker": "ARABREC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 32,
      "high": 32,
      "low": 31.3,
      "close": 32,
      "volume": 35376,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 32,
      "adj_high": 32,
      "adj_low": 31.3,
      "adj_close": 32,
      "adj_volume": 35376
    },
    {
      "ticker": "MASSALEH",
      "figi_ticker": "MASSALEH:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 36.7,
      "high": 36.7,
      "low": 36.7,
      "close": 36.7,
      "volume": 85,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 36.7,
      "adj_high": 36.7,
      "adj_low": 36.7,
      "adj_close": 36.7,
      "adj_volume": 85
    },
    {
      "ticker": "AREEC",
      "figi_ticker": "AREEC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 147,
      "high": 156,
      "low": 144,
      "close": 156,
      "volume": 65512,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 147,
      "adj_high": 156,
      "adj_low": 144,
      "adj_close": 156,
      "adj_volume": 65512
    },
    {
      "ticker": "TAM",
      "figi_ticker": "TAM:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 357,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 357,
      "adj_volume": 0
    },
    {
      "ticker": "SRE",
      "figi_ticker": "SRE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 336.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 336.5,
      "adj_volume": 0
    },
    {
      "ticker": "NRE",
      "figi_ticker": "NRE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 112,
      "high": 117,
      "low": 112,
      "close": 117,
      "volume": 47100,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 112,
      "adj_high": 117,
      "adj_low": 112,
      "adj_close": 117,
      "adj_volume": 47100
    },
    {
      "ticker": "URC",
      "figi_ticker": "URC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 59,
      "high": 59,
      "low": 59,
      "close": 59,
      "volume": 1800,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 59,
      "adj_high": 59,
      "adj_low": 59,
      "adj_close": 59,
      "adj_volume": 1800
    },
    {
      "ticker": "KRE",
      "figi_ticker": "KRE:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 47.7,
      "high": 48.1,
      "low": 47.7,
      "close": 48,
      "volume": 539000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 47.7,
      "adj_high": 48.1,
      "adj_low": 47.7,
      "adj_close": 48,
      "adj_volume": 539000
    },
    {
      "ticker": "WETHAQ",
      "figi_ticker": "WETHAQ:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 28.4,
      "high": 28.4,
      "low": 28.4,
      "close": 28.4,
      "volume": 48901,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 28.4,
      "adj_high": 28.4,
      "adj_low": 28.4,
      "adj_close": 28.4,
      "adj_volume": 48901
    },
    {
      "ticker": "AINS",
      "figi_ticker": "AINS:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 465.5,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 465.5,
      "adj_volume": 0
    },
    {
      "ticker": "KINS",
      "figi_ticker": "KINS:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": null,
      "high": null,
      "low": null,
      "close": 253,
      "volume": 0,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": null,
      "adj_high": null,
      "adj_low": null,
      "adj_close": 253,
      "adj_volume": 0
    },
    {
      "ticker": "GINS",
      "figi_ticker": "GINS:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 622,
      "high": 671,
      "low": 622,
      "close": 635,
      "volume": 1548,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 622,
      "adj_high": 671,
      "adj_low": 622,
      "adj_close": 635,
      "adj_volume": 1548
    },
    {
      "ticker": "ALIMTIAZ",
      "figi_ticker": "ALIMTIAZ:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 128,
      "high": 128,
      "low": 126,
      "close": 128,
      "volume": 38738,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 128,
      "adj_high": 128,
      "adj_low": 126,
      "adj_close": 128,
      "adj_volume": 38738
    },
    {
      "ticker": "AMWAL",
      "figi_ticker": "AMWAL:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 48,
      "high": 48,
      "low": 45.5,
      "close": 48,
      "volume": 50,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 48,
      "adj_high": 48,
      "adj_low": 45.5,
      "adj_close": 48,
      "adj_volume": 50
    },
    {
      "ticker": "GNAHC",
      "figi_ticker": "GNAHC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 35.8,
      "high": 36.5,
      "low": 35.8,
      "close": 36.5,
      "volume": 450000,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 35.8,
      "adj_high": 36.5,
      "adj_low": 35.8,
      "adj_close": 36.5,
      "adj_volume": 450000
    },
    {
      "ticker": "ASIYA",
      "figi_ticker": "ASIYA:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 37.6,
      "high": 37.6,
      "low": 37.5,
      "close": 37.5,
      "volume": 36665,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 37.6,
      "adj_high": 37.6,
      "adj_low": 37.5,
      "adj_close": 37.5,
      "adj_volume": 36665
    },
    {
      "ticker": "KSHC",
      "figi_ticker": "KSHC:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 30.9,
      "high": 30.9,
      "low": 28.5,
      "close": 30.9,
      "volume": 293567,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 30.9,
      "adj_high": 30.9,
      "adj_low": 28.5,
      "adj_close": 30.9,
      "adj_volume": 293567
    },
    {
      "ticker": "TAMINV",
      "figi_ticker": "TAMINV:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 280,
      "high": 280,
      "low": 280,
      "close": 280,
      "volume": 5250,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 280,
      "adj_high": 280,
      "adj_low": 280,
      "adj_close": 280,
      "adj_volume": 5250
    },
    {
      "ticker": "NOOR",
      "figi_ticker": "NOOR:KK",
      "figi": null,
      "date": "2018-04-23",
      "open": 47.4,
      "high": 48.3,
      "low": 47.4,
      "close": 48.2,
      "volume": 709253,
      "ex_dividend": 0,
      "split_ratio": 1,
      "adj_factor": 1,
      "adj_open": 47.4,
      "adj_high": 48.3,
      "adj_low": 47.4,
      "adj_close": 48.2,
      "adj_volume": 709253
    }
  ],
    "result_count": 145,
      "page_size": 100,
        "current_page": 1,
          "total_pages": 2,
            "api_call_credits": 1
}